### ISSUE TITLE
Should be archived in favor of `launchdarkly/go-client`

### ISSUE THREAD

**Issue by chenrui333** [mlafeldt/go-launchdarkly#1]
It is good idea to have the repo, however launchdarkly seems maintain a better go-client than the generated code. I think it might be put some reference to a better maintainable codebase.

https://github.com/launchdarkly/go-client

Thanks for your work though!

**Comment by mlafeldt** [comment]
Yeah, I know. AFAIK, their Go client didn't exist when I started working on the LaunchDarkly Terraform provider (which still depends on this repo).

**Comment by chenrui333** [comment]
that is true.
